# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

"""Functional correctness assertions for the bio_lab performance e2e test."""

import json
import re
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import Any

from loguru import logger
from performance_config import _ORIGINAL_SQLITE_PATH
from performance_query_cases import (
    EXPECTED_ANTIBODY_COUNT,
    EXPECTED_ANTIBODY_IDS,
    EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID,
    EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES,
    EXPECTED_CELL_COUNT,
    EXPECTED_CELL_IDS,
    EXPECTED_HUH7_CELL_SAMPLE_ID,
    EXPECTED_NEW_EXPERIMENT_STATUS,
    EXPECTED_PSEUDOVIRUS_COUNT,
    EXPECTED_PSEUDOVIRUS_IDS,
    EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID,
    TC_EXPECTED_ANSWER_ASSERTIONS,
    TC_NON_BLOCKING_REVIEW_CASES,
    TCW_DB_EFFECT_ASSERTIONS,
    TCW_EXPECTED_ANSWER_ASSERTIONS,
)


def _find_created_experiment_id(db_path: Path, today: str) -> int | None:
    """Query the bio_lab.sqlite DB for the experiment created by Q1.

    A "valid Q1 creation" is a row in ``neutralization_experiments`` joined
    with ``experiments`` that satisfies ALL of:
      - inhibitor_sample_id  = EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID
      - pseudovirus_sample_id = EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID
      - cell_sample_id       = EXPECTED_HUH7_CELL_SAMPLE_ID
      - experiments.status   = EXPECTED_NEW_EXPERIMENT_STATUS
      - experiments.start_date = today (the test run date)

    Returns the experiment id (int) if found, else None. The id is
    auto-generated by the agent's INSERT script (e.g. 902036 in the deepseek
    reference run) so it cannot be predicted ahead of time.
    """

    if not db_path.exists():
        return None
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            """
            SELECT ne.id
            FROM neutralization_experiments ne
            JOIN experiments e ON ne.id = e.id
            WHERE ne.inhibitor_sample_id = ?
              AND ne.pseudovirus_sample_id = ?
              AND ne.cell_sample_id = ?
              AND e.status = ?
              AND e.start_date = ?
            ORDER BY ne.id DESC
            LIMIT 1
            """,
            (
                EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID,
                EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID,
                EXPECTED_HUH7_CELL_SAMPLE_ID,
                EXPECTED_NEW_EXPERIMENT_STATUS,
                today,
            ),
        )
        row = cur.fetchone()
        return int(row[0]) if row and row[0] is not None else None
    finally:
        conn.close()


find_created_experiment_id = _find_created_experiment_id


def _find_created_tcw_neutralization_experiment_ids(
    db_path: Path,
    *,
    today: str,
    antibody_name: str,
    pseudovirus_name: str,
    cell_name: str,
    status: str,
) -> list[int]:
    if not db_path.exists():
        return []
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            """
            SELECT ne.id
            FROM neutralization_experiments ne
            JOIN experiments e ON ne.id = e.id
            JOIN antibody_samples antibody_sample ON ne.inhibitor_sample_id = antibody_sample.id
            JOIN antibodies antibody ON antibody_sample.antibody_id = antibody.id
            JOIN proteins antibody_protein ON antibody.id = antibody_protein.id
            JOIN pseudovirus_samples pseudovirus_sample
              ON ne.pseudovirus_sample_id = pseudovirus_sample.id
            JOIN pseudoviruses pseudovirus ON pseudovirus_sample.pseudovirus_id = pseudovirus.id
            JOIN cell_samples cell_sample ON ne.cell_sample_id = cell_sample.id
            JOIN cells cell ON cell_sample.cell_id = cell.id
            WHERE antibody_protein.name = ?
              AND pseudovirus.name = ?
              AND cell.name = ?
              AND e.status = ?
              AND e.start_date = ?
            ORDER BY ne.id DESC
            """,
            (antibody_name, pseudovirus_name, cell_name, status, today),
        )
        return [int(row[0]) for row in cur.fetchall() if row and row[0] is not None]
    finally:
        conn.close()


def _find_any_today_neutralization_experiment_ids(db_path: Path, *, today: str, status: str | None = None) -> list[int]:
    """All neutralization experiments created today (optionally filtered by status)."""
    if not db_path.exists():
        return []
    conn = sqlite3.connect(str(db_path))
    try:
        if status is not None:
            cur = conn.execute(
                """SELECT ne.id FROM neutralization_experiments ne
                   JOIN experiments e ON ne.id = e.id
                   WHERE e.start_date = ? AND e.status = ?
                   ORDER BY ne.id DESC""",
                (today, status),
            )
        else:
            cur = conn.execute(
                """SELECT ne.id FROM neutralization_experiments ne
                   JOIN experiments e ON ne.id = e.id
                   WHERE e.start_date = ?
                   ORDER BY ne.id DESC""",
                (today,),
            )
        return [int(row[0]) for row in cur.fetchall() if row and row[0] is not None]
    finally:
        conn.close()


def _find_today_neutralization_experiment_ids_by_assets(
    db_path: Path,
    *,
    today: str,
    antibody_name: str | None = None,
    pseudovirus_name: str | None = None,
    cell_name: str | None = None,
) -> list[int]:
    """Today's neutralization experiments matching any of the provided asset names.

    A None asset name means "don't filter on that asset". This is used by the
    experiment_not_created check: if the list is empty, no matching experiment
    was created today (i.e. the agent correctly did NOT create).
    """
    if not db_path.exists():
        return []
    clauses: list[str] = ["e.start_date = ?"]
    params: list[Any] = [today]
    if antibody_name is not None:
        clauses.append(
            "EXISTS (SELECT 1 FROM antibody_samples abs JOIN antibodies abt ON abs.antibody_id=abt.id "
            "JOIN proteins pr ON abt.id=pr.id WHERE abs.id=ne.inhibitor_sample_id AND pr.name=?)"
        )
        params.append(antibody_name)
    if pseudovirus_name is not None:
        clauses.append(
            "EXISTS (SELECT 1 FROM pseudovirus_samples pss JOIN pseudoviruses pv ON pss.pseudovirus_id=pv.id "
            "WHERE pss.id=ne.pseudovirus_sample_id AND pv.name LIKE ?)"
        )
        params.append(f"%{pseudovirus_name}%")
    if cell_name is not None:
        clauses.append(
            "EXISTS (SELECT 1 FROM cell_samples cs JOIN cells c ON cs.cell_id=c.id "
            "WHERE cs.id=ne.cell_sample_id AND (c.name LIKE ? OR c.aliases LIKE ?))"
        )
        params.extend([f"%{cell_name}%", f"%{cell_name}%"])
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            f"""SELECT ne.id FROM neutralization_experiments ne
                JOIN experiments e ON ne.id = e.id
                WHERE {" AND ".join(clauses)}
                ORDER BY ne.id DESC""",
            tuple(params),
        )
        return [int(row[0]) for row in cur.fetchall() if row and row[0] is not None]
    finally:
        conn.close()


def _find_today_experiments_by_operator_name(db_path: Path, *, today: str, operator_name: str) -> list[int]:
    """Today's experiments whose submitter or operator maps to a user with the given name."""
    if not db_path.exists():
        return []
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            """SELECT e.id FROM experiments e
               WHERE e.start_date = ?
                 AND (e.submitter IN (SELECT id FROM users WHERE name LIKE ?)
                      OR e.operator IN (SELECT id FROM users WHERE name LIKE ?))
               ORDER BY e.id DESC""",
            (today, f"%{operator_name}%", f"%{operator_name}%"),
        )
        return [int(row[0]) for row in cur.fetchall() if row and row[0] is not None]
    finally:
        conn.close()


def _experiment_status_count(db_path: Path, *, experiment_id: int, status: str) -> int:
    """Count experiments with the given id and status (used by experiment_not_modified)."""
    if not db_path.exists():
        return 0
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute(
            "SELECT COUNT(*) FROM experiments WHERE id = ? AND status = ?",
            (experiment_id, status),
        )
        return int(cur.fetchone()[0] or 0)
    finally:
        conn.close()


def _antibody_row_count(db_path: Path, *, antibody_id: int) -> int:
    """Count antibodies rows with the given id (used by antibody_not_deleted)."""
    if not db_path.exists():
        return 0
    conn = sqlite3.connect(str(db_path))
    try:
        cur = conn.execute("SELECT COUNT(*) FROM antibodies WHERE id = ?", (antibody_id,))
        return int(cur.fetchone()[0] or 0)
    finally:
        conn.close()


def _table_exists_by_globs(db_path: Path, globs: list[str]) -> bool:
    """True if any table name in sqlite_master matches any of the LIKE globs."""
    if not db_path.exists():
        return False
    conn = sqlite3.connect(str(db_path))
    try:
        or_clauses = " OR ".join(["name LIKE ?" for _ in globs])
        cur = conn.execute(
            f"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND ({or_clauses})",
            tuple(globs),
        )
        return int(cur.fetchone()[0] or 0) > 0
    finally:
        conn.close()


def capture_tcw_database_effects(db_path: Path, query_key: str) -> dict[str, Any]:
    """Capture write-side evidence before a TC-W case database rollback."""
    assertion_spec = TCW_DB_EFFECT_ASSERTIONS.get(query_key)
    if not assertion_spec:
        return {}

    today = datetime.now().strftime("%Y-%m-%d")
    kind = assertion_spec["kind"]
    expected: dict[str, Any] = {"kind": kind, "start_date": today}

    if kind == "neutralization_created":
        experiment_ids = _find_created_tcw_neutralization_experiment_ids(
            db_path,
            today=today,
            antibody_name=assertion_spec["antibody_name"],
            pseudovirus_name=assertion_spec["pseudovirus_name"],
            cell_name=assertion_spec["cell_name"],
            status=assertion_spec["status"],
        )
        expected.update(
            {
                "antibody_name": assertion_spec["antibody_name"],
                "pseudovirus_name": assertion_spec["pseudovirus_name"],
                "cell_name": assertion_spec["cell_name"],
                "status": assertion_spec["status"],
            }
        )
        return {
            "kind": kind,
            "expected": expected,
            "created_experiment_ids": experiment_ids,
            "matched": bool(experiment_ids),
        }

    if kind == "experiment_not_created":
        # PASS when no matching experiment was created today.
        status = assertion_spec.get("status")
        operator_name = assertion_spec.get("operator_name")
        antibody_name = assertion_spec.get("antibody_name")
        pseudovirus_name = assertion_spec.get("pseudovirus_name")
        cell_name = assertion_spec.get("cell_name")
        if operator_name is not None:
            created_ids = _find_today_experiments_by_operator_name(db_path, today=today, operator_name=operator_name)
            expected["operator_name"] = operator_name
        elif status is not None and antibody_name is None and pseudovirus_name is None and cell_name is None:
            created_ids = _find_any_today_neutralization_experiment_ids(db_path, today=today, status=status)
            expected["status"] = status
        elif antibody_name is None and pseudovirus_name is None and cell_name is None:
            created_ids = _find_any_today_neutralization_experiment_ids(db_path, today=today)
        else:
            created_ids = _find_today_neutralization_experiment_ids_by_assets(
                db_path,
                today=today,
                antibody_name=antibody_name,
                pseudovirus_name=pseudovirus_name,
                cell_name=cell_name,
            )
            expected.update(
                {"antibody_name": antibody_name, "pseudovirus_name": pseudovirus_name, "cell_name": cell_name}
            )
        return {
            "kind": kind,
            "expected": expected,
            "created_experiment_ids": created_ids,
            "matched": not created_ids,
        }

    if kind == "experiment_not_modified":
        experiment_id = assertion_spec["experiment_id"]
        forbidden_status = assertion_spec["forbidden_status"]
        count = _experiment_status_count(db_path, experiment_id=experiment_id, status=forbidden_status)
        expected.update({"experiment_id": experiment_id, "forbidden_status": forbidden_status})
        return {
            "kind": kind,
            "expected": expected,
            "status_count": count,
            "matched": count == 0,
        }

    if kind == "antibody_not_deleted":
        antibody_id = assertion_spec["antibody_id"]
        count = _antibody_row_count(db_path, antibody_id=antibody_id)
        expected["antibody_id"] = antibody_id
        return {
            "kind": kind,
            "expected": expected,
            "antibody_count": count,
            "matched": count == 0,
        }

    if kind == "table_absent_no_write":
        globs = assertion_spec.get("table_globs", ["%column%", "%dictionary%"])
        table_exists = _table_exists_by_globs(db_path, globs)
        today_experiments = _find_any_today_neutralization_experiment_ids(db_path, today=today)
        expected["table_globs"] = globs
        return {
            "kind": kind,
            "expected": expected,
            "table_exists": table_exists,
            "today_experiment_count": len(today_experiments),
            "matched": not table_exists and not today_experiments,
        }

    return {
        "kind": kind,
        "matched": False,
        "error": f"unsupported TC-W database effect kind: {kind}",
    }


def _strip_sql_fences(sql_text: str) -> str:
    sql_text = re.sub(r"^\s*```(?:sql)?\s*", "", sql_text, flags=re.IGNORECASE)
    sql_text = re.sub(r"\s*```\s*$", "", sql_text)
    return sql_text.strip()


def _strip_leading_sql_comments(statement: str) -> str:
    text = statement.strip()
    while True:
        new_text = re.sub(r"^\s*--[^\n]*(?:\n|$)", "", text)
        new_text = re.sub(r"^\s*/\*.*?\*/", "", new_text, flags=re.DOTALL).strip()
        if new_text == text:
            return text
        text = new_text


def _split_sql_statements(sql_text: str) -> list[str]:
    statements: list[str] = []
    current: list[str] = []
    in_single = False
    in_double = False
    in_line_comment = False
    in_block_comment = False
    i = 0
    while i < len(sql_text):
        char = sql_text[i]
        next_char = sql_text[i + 1] if i + 1 < len(sql_text) else ""

        if in_line_comment:
            current.append(char)
            if char == "\n":
                in_line_comment = False
            i += 1
            continue
        if in_block_comment:
            current.append(char)
            if char == "*" and next_char == "/":
                current.append(next_char)
                in_block_comment = False
                i += 2
            else:
                i += 1
            continue
        if in_single:
            current.append(char)
            if char == "'" and next_char == "'":
                current.append(next_char)
                i += 2
                continue
            if char == "'":
                in_single = False
            i += 1
            continue
        if in_double:
            current.append(char)
            if char == '"' and next_char == '"':
                current.append(next_char)
                i += 2
                continue
            if char == '"':
                in_double = False
            i += 1
            continue

        if char == "-" and next_char == "-":
            current.extend([char, next_char])
            in_line_comment = True
            i += 2
            continue
        if char == "/" and next_char == "*":
            current.extend([char, next_char])
            in_block_comment = True
            i += 2
            continue
        if char == "'":
            current.append(char)
            in_single = True
            i += 1
            continue
        if char == '"':
            current.append(char)
            in_double = True
            i += 1
            continue
        if char == ";":
            statement = "".join(current).strip()
            if statement:
                statements.append(statement)
            current = []
            i += 1
            continue

        current.append(char)
        i += 1

    statement = "".join(current).strip()
    if statement:
        statements.append(statement)
    return statements


def _normalize_sql_value(value: Any) -> str:
    if value is None:
        return "<NULL>"
    if isinstance(value, float):
        return f"{value:.12g}"
    return str(value)


def _canonicalize_rows(rows: list[tuple[Any, ...]]) -> list[tuple[str, ...]]:
    return sorted(tuple(_normalize_sql_value(value) for value in row) for row in rows)


def _execute_sql_result_sets(
    db_path: Path, sql_text: str, source: str
) -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    result_sets: list[dict[str, Any]] = []
    errors: list[dict[str, str]] = []
    cleaned_sql = _strip_sql_fences(sql_text)
    statements = _split_sql_statements(cleaned_sql)
    conn = sqlite3.connect(f"file:{db_path.resolve().as_posix()}?mode=ro", uri=True)
    try:
        for idx, statement in enumerate(statements, 1):
            executable = _strip_leading_sql_comments(statement)
            if not executable:
                continue
            first_token = executable.split(None, 1)[0].lower()
            if first_token not in {"select", "with", "pragma"}:
                continue
            try:
                cur = conn.execute(statement)
                columns = [col[0] for col in cur.description or []]
                rows = cur.fetchall() if cur.description else []
            except Exception as exc:
                errors.append(
                    {
                        "source": source,
                        "statement_index": str(idx),
                        "error": str(exc),
                        "sql": statement,
                    }
                )
                continue
            result_sets.append(
                {
                    "source": source,
                    "statement_index": idx,
                    "sql": statement,
                    "columns": columns,
                    "row_count": len(rows),
                    "canonical_rows": _canonicalize_rows(rows),
                    "preview_rows": [list(row) for row in rows[:10]],
                }
            )
    finally:
        conn.close()
    return result_sets, errors


def _matches_sql_evidence(
    generated_result_sets: list[dict[str, Any]],
    rule: dict[str, Any],
) -> dict[str, Any] | None:
    """Match result-backed evidence without constraining the generated SQL shape."""
    required_sql_terms = [str(term).casefold() for term in rule.get("required_sql_terms", [])]
    null_column = rule.get("null_column")
    allow_empty_result = rule.get("allow_empty_result", True)

    for result in generated_result_sets:
        sql_text = result["sql"].casefold()
        if not all(term in sql_text for term in required_sql_terms):
            continue

        has_empty_result = allow_empty_result and result["row_count"] == 0
        has_null_result = (
            isinstance(null_column, int)
            and result["row_count"] > 0
            and all(len(row) > null_column and row[null_column] == "<NULL>" for row in result["canonical_rows"])
        )
        if has_empty_result or has_null_result:
            return {
                "source": result["source"],
                "statement_index": result["statement_index"],
                "row_count": result["row_count"],
                "preview_rows": result["preview_rows"],
                "sql": result["sql"],
            }

    return None


def _record_non_blocking_tc_reviews(
    response_by_key: dict[str, dict[str, Any]],
    tc_results: dict[str, dict[str, Any]],
) -> None:
    """Record TC semantics that still need a human decision without failing the run."""
    for query_key, review_spec in TC_NON_BLOCKING_REVIEW_CASES.items():
        response = response_by_key.get(query_key)
        if response is None:
            continue

        reason = review_spec["reason"]
        review_status = review_spec.get("status", "requires_manual_review")

        review = {
            "blocking": False,
            "reason": reason,
            "sql_files": response.get("sql_files", []),
            "answer_preview": response.get("final_answer", "")[:500],
        }
        existing_result = tc_results.get(query_key)
        if existing_result is None:
            tc_results[query_key] = {"status": review_status, "manual_review": review}
        else:
            existing_result["manual_review"] = review
        logger.warning(f"  {query_key}: {review_status} (non-blocking): {reason}")


def _answer_contains(answer: str, term: Any) -> bool:
    return str(term).casefold() in answer.casefold()


def _missing_answer_terms(answer: str, terms: list[Any] | tuple[Any, ...] | set[Any]) -> list[str]:
    return [str(term) for term in terms if not _answer_contains(answer, term)]


def _missing_answer_term_groups(
    answer: str,
    term_groups: list[list[Any]] | tuple[tuple[Any, ...], ...],
) -> list[list[str]]:
    return [
        [str(term) for term in term_group]
        for term_group in term_groups
        if not any(_answer_contains(answer, term) for term in term_group)
    ]


def _match_answer_terms(answer: str, assertion_spec: dict[str, Any]) -> dict[str, Any]:
    """Match required terms / any-term-groups.

    ``soft_required_terms`` are query-echo terms (entity names, concepts copied
    from the query) that need not appear verbatim in a correct answer.  They are
    checked but never gate ``matched`` — a missing soft term is surfaced as a
    non-blocking advisory by the caller.

    ``absence_answer_terms`` is reported but no longer gates ``matched``:
    a missing absence phrase is handled as a non-blocking manual-review by the
    caller (``_check_answer_assertion``), so an "absent" answer that otherwise
    states the expected facts still counts as correct.
    """
    required_terms = assertion_spec.get("required_terms", [])
    soft_required_terms = assertion_spec.get("soft_required_terms", [])
    required_any_term_groups = assertion_spec.get("required_any_term_groups", [])
    absence_answer_terms = assertion_spec.get("absence_answer_terms", [])
    missing_terms = _missing_answer_terms(answer, required_terms)
    missing_soft_terms = _missing_answer_terms(answer, soft_required_terms)
    missing_groups = _missing_answer_term_groups(answer, required_any_term_groups)
    has_absence_answer = not absence_answer_terms or any(
        _answer_contains(answer, term) for term in absence_answer_terms
    )
    matched = not missing_terms and not missing_groups
    return {
        "matched": matched,
        "missing_terms": missing_terms,
        "missing_soft_terms": missing_soft_terms,
        "missing_any_term_groups": missing_groups,
        "has_absence_answer": has_absence_answer,
        "missing_absence_terms": [] if has_absence_answer else [str(term) for term in absence_answer_terms],
    }


def _collect_sql_evidence(response: dict[str, Any]) -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    """Execute the agent-generated SQL files against the fixture and return result sets + errors."""
    generated_result_sets: list[dict[str, Any]] = []
    sql_evidence_errors: list[dict[str, str]] = []
    for sql_path in response.get("sql_files", []):
        sql_file = Path(sql_path)
        if ".context" in sql_file.parts or ".memory" in sql_file.parts:
            continue
        if not sql_file.exists():
            sql_evidence_errors.append({"source": str(sql_file), "statement_index": "0", "error": "file not found"})
            continue
        result_sets, errors = _execute_sql_result_sets(
            Path(_ORIGINAL_SQLITE_PATH),
            sql_file.read_text(encoding="utf-8"),
            source=str(sql_file),
        )
        generated_result_sets.extend(result_sets)
        sql_evidence_errors.extend(errors)
    return generated_result_sets, sql_evidence_errors


def _check_answer_assertion(response: dict[str, Any], assertion_spec: dict[str, Any]) -> dict[str, Any]:
    """Evaluate one answer assertion and return a result dict (caller handles failures)."""
    if assertion_spec.get("allow_human_feedback_pass") and response.get("hitl_triggered"):
        return {
            "status": "passed_by_human_feedback",
            "expected_summary": assertion_spec.get("expected_summary"),
            "answer_preview": response.get("final_answer", "")[:500],
            "blocking": assertion_spec.get("blocking", True),
            "manual_review_required": False,
        }

    answer = str(response.get("final_answer", ""))
    term_result = _match_answer_terms(answer, assertion_spec)
    sql_evidence_rule = assertion_spec.get("sql_evidence")
    sql_evidence_match = None
    sql_evidence_errors: list[dict[str, str]] = []
    if sql_evidence_rule:
        generated_result_sets, sql_evidence_errors = _collect_sql_evidence(response)
        sql_evidence_match = _matches_sql_evidence(generated_result_sets, sql_evidence_rule)

    blocking = assertion_spec.get("blocking", True)
    hard_matched = bool(term_result["matched"]) and (
        not sql_evidence_rule or (not sql_evidence_errors and sql_evidence_match is not None)
    )

    # Absence advisory: if an absence vocabulary is configured but the answer
    # shows none of it, defer to manual review instead of failing the run.
    if assertion_spec.get("absence_answer_terms") and not term_result["has_absence_answer"]:
        return {
            "status": "requires_manual_review",
            "blocking": False,
            "expected_summary": assertion_spec.get("expected_summary"),
            "missing_terms": term_result["missing_terms"],
            "missing_soft_terms": term_result["missing_soft_terms"],
            "missing_any_term_groups": term_result["missing_any_term_groups"],
            "missing_absence_terms": term_result["missing_absence_terms"],
            "sql_evidence": sql_evidence_match,
            "sql_evidence_errors": sql_evidence_errors,
            "answer_preview": answer[:500],
            "manual_review_required": True,
        }

    if hard_matched:
        status = "passed_by_answer_assertion"
    else:
        status = "non_blocking_answer_assertion_failed" if not blocking else "failed"
    return {
        "status": status,
        "blocking": blocking,
        "expected_summary": assertion_spec.get("expected_summary"),
        "missing_terms": term_result["missing_terms"],
        "missing_soft_terms": term_result["missing_soft_terms"],
        "missing_any_term_groups": term_result["missing_any_term_groups"],
        "missing_absence_terms": term_result["missing_absence_terms"],
        "sql_evidence": sql_evidence_match,
        "sql_evidence_errors": sql_evidence_errors,
        "answer_preview": answer[:500],
        "manual_review_required": False,
    }


def _format_answer_failure(query_key: str, result: dict[str, Any], response: dict[str, Any]) -> str:
    final_answer = str(response.get("final_answer", ""))
    return (
        f"{query_key} answer fact assertion failed. Expected: {result.get('expected_summary')}\n"
        f"Missing terms: {result['missing_terms'] or 'NONE'}\n"
        f"Missing soft terms: {result.get('missing_soft_terms') or 'NONE'}\n"
        f"Missing any-term groups: {result['missing_any_term_groups'] or 'NONE'}\n"
        f"Missing absence terms: {result['missing_absence_terms'] or 'NONE'}\n"
        f"SQL evidence: {result.get('sql_evidence') or 'NONE'}\n"
        f"SQL evidence errors: {result.get('sql_evidence_errors') or 'NONE'}\n"
        f"Final answer preview:\n{final_answer[:1000]}"
    )


def _run_answer_checks(
    answer_specs: dict[str, dict[str, Any]],
    response_by_key: dict[str, dict[str, Any]],
) -> tuple[dict[str, dict[str, Any]], list[str]]:
    results: dict[str, dict[str, Any]] = {}
    if not any(key in answer_specs or key in TC_NON_BLOCKING_REVIEW_CASES for key in response_by_key):
        return results, []
    failure_messages: list[str] = []
    for query_key, assertion_spec in answer_specs.items():
        if query_key not in response_by_key:
            continue
        result = _check_answer_assertion(response_by_key[query_key], assertion_spec)
        results[query_key] = result
        status = result["status"]
        if status == "requires_manual_review":
            logger.warning(f"  {query_key}: ⚠️ absence language missing — requires manual review (non-blocking)")
            if result.get("missing_soft_terms"):
                logger.warning(f"  {query_key}: ⚠️ missing soft terms (non-blocking): {result['missing_soft_terms']}")
            continue
        if status.startswith("passed"):
            if result.get("missing_soft_terms"):
                logger.warning(
                    f"  {query_key}: ⚠️ passed but missing soft terms (non-blocking): {result['missing_soft_terms']}"
                )
            logger.info(f"  {query_key}: ✅ {status}")
            continue
        message = _format_answer_failure(query_key, result, response_by_key[query_key])
        if result["blocking"]:
            failure_messages.append(message)
            logger.error(f"  {query_key}: ❌ answer is missing expected facts")
        else:
            logger.warning(f"  {query_key}: {status} (non-blocking): {message}")
    return results, failure_messages


def _write_answer_report(
    report_dir: Path,
    report_name: str,
    results: dict[str, dict[str, Any]],
    failure_messages: list[str],
) -> None:
    report_path = report_dir / report_name
    report_path.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")
    logger.info(f"Answer results report: {report_path}")
    if failure_messages:
        raise AssertionError(
            f"{len(failure_messages)} answer assertion(s) failed. Full report: {report_path}\n\n"
            + "\n\n".join(failure_messages)
        )


def verify_tc_answer_assertions(
    response_by_key: dict[str, dict[str, Any]],
    report_dir: Path,
) -> dict[str, dict[str, Any]]:
    """Verify TC (问数) answer assertions only."""
    logger.info("=" * 60)
    logger.info("TC answer fact checks")
    results, failure_messages = _run_answer_checks(TC_EXPECTED_ANSWER_ASSERTIONS, response_by_key)
    _record_non_blocking_tc_reviews(response_by_key, results)
    _write_answer_report(report_dir, "tc_answer_functional_results_v3.json", results, failure_messages)
    logger.info("=" * 60)
    return results


def verify_tcw_answer_assertions(
    response_by_key: dict[str, dict[str, Any]],
    report_dir: Path,
) -> dict[str, dict[str, Any]]:
    """Verify TC-W (流程) answer assertions only."""
    logger.info("=" * 60)
    logger.info("TC-W answer fact checks")
    results, failure_messages = _run_answer_checks(TCW_EXPECTED_ANSWER_ASSERTIONS, response_by_key)
    _write_answer_report(report_dir, "tcw_answer_functional_results_v3.json", results, failure_messages)
    logger.info("=" * 60)
    return results


def verify_tcw_database_effects(
    response_by_key: dict[str, dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    """Verify TC-W write-side database effects (read pre-captured ``db_effects``)."""
    tcw_results: dict[str, dict[str, Any]] = {}
    failure_messages: list[str] = []

    for query_key, assertion_spec in TCW_DB_EFFECT_ASSERTIONS.items():
        response = response_by_key.get(query_key)
        if response is None:
            continue

        db_effects = response.get("db_effects") or {}
        created_ids = db_effects.get("created_experiment_ids") or []
        matched = bool(db_effects.get("matched"))
        blocking = assertion_spec.get("blocking", True)
        answer = str(response.get("final_answer", ""))
        # require_answer_mentions_id is a non-blocking advisory: a missing id
        # is logged as a warning but no longer fails the assertion.
        missing_answer_id = bool(
            matched
            and assertion_spec.get("require_answer_mentions_id")
            and not any(str(eid) in answer for eid in created_ids)
        )
        status = "passed" if matched else ("non_blocking_failed" if not blocking else "failed")
        tcw_results[f"{query_key}_db_effect"] = {
            "status": status,
            "db_effects": db_effects,
            "answer_preview": answer[:500],
            "missing_answer_id": missing_answer_id,
            "blocking": blocking,
        }

        if matched:
            logger.info(f"  {query_key}: ✅ DB effect matched ({assertion_spec['kind']})")
            if missing_answer_id:
                logger.warning(f"  {query_key}: ⚠️ answer did not mention created id (non-blocking)")
            continue

        if not blocking:
            logger.warning(
                f"  {query_key}: ⚠️ DB effect not matched but blocking=False (non-blocking): {assertion_spec['kind']}"
            )
            continue

        failure_messages.append(
            f"{query_key} DB effect assertion failed (kind={assertion_spec['kind']}).\n"
            f"Captured DB effects: {db_effects or 'NONE'}\n"
            f"Final answer preview:\n{answer[:1000]}"
        )
        logger.error(f"  {query_key}: ❌ DB effect assertion failed")

    if failure_messages:
        raise AssertionError(
            f"{len(failure_messages)} TC-W DB effect assertion(s) failed.\n\n" + "\n\n".join(failure_messages)
        )
    return tcw_results


def verify_default_replay_assertions(
    response_by_key: dict[str, dict[str, Any]],
    workspace_dir: Path,
    report_dir: Path,
) -> tuple[dict[str, dict[str, Any]], int | None]:
    """Verify the default 7-question session replay (Q1 create_experiment … Q7)."""
    logger.info("=" * 60)
    logger.info("Default replay correctness checks:")

    db_path = workspace_dir / "bio_lab.sqlite"
    today_str = datetime.now().strftime("%Y-%m-%d")
    functional_results: dict[str, dict[str, Any]] = {}
    created_experiment_id: int | None = None

    # ---- Q1: create_experiment -----------------------------------------
    if "create_experiment" in response_by_key:
        created_experiment_id = _find_created_experiment_id(db_path, today_str)
        q1_answer = response_by_key["create_experiment"].get("final_answer", "")
        functional_results["create_experiment"] = {
            "created_experiment_id": created_experiment_id,
            "answer_preview": q1_answer[:300],
        }
        assert created_experiment_id is not None, (
            f"Q1 (create_experiment) FAILED: no new neutralization_experiments "
            f"row found in {db_path} with inhibitor_sample_id="
            f"{EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID}, pseudovirus_sample_id="
            f"{EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID}, cell_sample_id="
            f"{EXPECTED_HUH7_CELL_SAMPLE_ID}, status="
            f"{EXPECTED_NEW_EXPERIMENT_STATUS!r}, start_date={today_str!r}. "
            f"This means the agent did NOT actually create the experiment — "
            f"most likely NL2SQL generated a wrong lookup SQL (e.g. confused "
            f"the antibody NAME 'BD55-1111' with the numeric id column) and "
            f"the create workflow aborted before INSERT. Final answer was:\n"
            f"{q1_answer[:1000]}"
        )
        assert str(created_experiment_id) in q1_answer, (
            f"Q1 (create_experiment): the agent created experiment "
            f"{created_experiment_id} in the DB but its final answer does "
            f"not mention this id. Final answer was:\n{q1_answer[:1000]}"
        )
        logger.info(
            f"  Q1 create_experiment: ✅ experiment {created_experiment_id} "
            f"created (inhibitor={EXPECTED_BD55_1111_ANTIBODY_SAMPLE_ID}, "
            f"pseudovirus={EXPECTED_XBB15_PSEUDOVIRUS_SAMPLE_ID}, "
            f"cell={EXPECTED_HUH7_CELL_SAMPLE_ID}, status="
            f"{EXPECTED_NEW_EXPERIMENT_STATUS!r}, date={today_str})"
        )
    else:
        logger.warning(
            "  Q1 create_experiment: SKIPPED (not in query sequence — "
            "--skip_slow or --quick mode). Q3/Q7 id-consistency checks "
            "will also be skipped."
        )

    # ---- Q2: find_antibody_neutralization ------------------------------
    if "find_antibody_neutralization" in response_by_key:
        q2_answer = response_by_key["find_antibody_neutralization"].get("final_answer", "")
        missing = [name for name in EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES if name not in q2_answer]
        functional_results["find_antibody_neutralization"] = {
            "missing_pseudoviruses": missing,
            "answer_preview": q2_answer[:300],
        }
        assert not missing, (
            f"Q2 (find_antibody_neutralization) FAILED: the agent's final "
            f"answer is missing {len(missing)} of the "
            f"{len(EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES)} expected "
            f"pseudovirus names (BD-368 neutralizes with IC50<0.1): "
            f"missing={missing}. Expected all of "
            f"{sorted(EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES)}. "
            f"This usually means the NL2SQL joined on the wrong column "
            f"(e.g. antibodies.id='BD-368' instead of proteins.name='BD-368') "
            f"and returned an empty / partial result. Final answer was:\n"
            f"{q2_answer[:1500]}"
        )
        logger.info(
            f"  Q2 find_antibody_neutralization: ✅ all "
            f"{len(EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES)} expected "
            f"pseudoviruses present "
            f"({sorted(EXPECTED_BD368_NEUTRALIZED_PSEUDOVIRUSES)})"
        )
    else:
        logger.info("  Q2 find_antibody_neutralization: SKIPPED (not in query sequence).")

    # ---- Q3: find_recent_experiment ------------------------------------
    if "find_recent_experiment" in response_by_key:
        q3_answer = response_by_key["find_recent_experiment"].get("final_answer", "")
        functional_results["find_recent_experiment"] = {
            "expected_experiment_id": created_experiment_id,
            "answer_preview": q3_answer[:300],
        }
        if created_experiment_id is None:
            logger.warning(
                "  Q3 find_recent_experiment: SKIPPED (Q1 was not run, so "
                "no reference experiment_id to assert against)."
            )
        else:
            assert str(created_experiment_id) in q3_answer, (
                f"Q3 (find_recent_experiment) FAILED: the most recent "
                f"XBB.1.5+BD55-1111 experiment is {created_experiment_id} "
                f"(created in Q1), but the agent's final answer does not "
                f"mention this id. This usually means the lookup SQL used "
                f"the wrong column (e.g. pv.name=123 instead of "
                f"pv.name='XBB.1.5') and returned no rows. "
                f"Final answer was:\n{q3_answer[:1500]}"
            )
            logger.info(f"  Q3 find_recent_experiment: ✅ reports experiment {created_experiment_id} (matches Q1)")
    else:
        logger.info("  Q3 find_recent_experiment: SKIPPED (not in query sequence).")

    # ---- Q4: count_cells -----------------------------------------------
    if "count_cells" in response_by_key:
        q4_answer = response_by_key["count_cells"].get("final_answer", "")
        missing_ids = [cid for cid in EXPECTED_CELL_IDS if cid not in q4_answer]
        functional_results["count_cells"] = {
            "expected_count": EXPECTED_CELL_COUNT,
            "expected_ids": sorted(EXPECTED_CELL_IDS),
            "missing_ids": missing_ids,
            "answer_preview": q4_answer[:300],
        }
        assert str(EXPECTED_CELL_COUNT) in q4_answer, (
            f"Q4 (count_cells) FAILED: expected {EXPECTED_CELL_COUNT} cells "
            f"in the DB but the agent's final answer does not mention this "
            f"count. Final answer was:\n{q4_answer[:1000]}"
        )
        assert not missing_ids, (
            f"Q4 (count_cells) FAILED: the agent's final answer is missing "
            f"cell id(s) {missing_ids} (expected all of "
            f"{sorted(EXPECTED_CELL_IDS)}). Final answer was:\n{q4_answer[:1000]}"
        )
        logger.info(f"  Q4 count_cells: ✅ {EXPECTED_CELL_COUNT} cells, ids={sorted(EXPECTED_CELL_IDS)}")
    else:
        logger.info("  Q4 count_cells: SKIPPED (not in query sequence).")

    # ---- Q5: count_viruses ---------------------------------------------
    if "count_viruses" in response_by_key:
        q5_answer = response_by_key["count_viruses"].get("final_answer", "")
        missing_ids = [vid for vid in EXPECTED_PSEUDOVIRUS_IDS if vid not in q5_answer]
        functional_results["count_viruses"] = {
            "expected_count": EXPECTED_PSEUDOVIRUS_COUNT,
            "expected_ids": sorted(EXPECTED_PSEUDOVIRUS_IDS),
            "missing_ids": missing_ids,
            "answer_preview": q5_answer[:300],
        }
        assert str(EXPECTED_PSEUDOVIRUS_COUNT) in q5_answer, (
            f"Q5 (count_viruses) FAILED: expected {EXPECTED_PSEUDOVIRUS_COUNT} "
            f"pseudoviruses in the DB but the agent's final answer does not "
            f"mention this count. Final answer was:\n{q5_answer[:1000]}"
        )
        assert not missing_ids, (
            f"Q5 (count_viruses) FAILED: the agent's final answer is missing "
            f"pseudovirus id(s) {missing_ids} (expected all of "
            f"{sorted(EXPECTED_PSEUDOVIRUS_IDS)}). Final answer was:\n{q5_answer[:1000]}"
        )
        logger.info(
            f"  Q5 count_viruses: ✅ {EXPECTED_PSEUDOVIRUS_COUNT} pseudoviruses, ids={sorted(EXPECTED_PSEUDOVIRUS_IDS)}"
        )
    else:
        logger.info("  Q5 count_viruses: SKIPPED (not in query sequence).")

    # ---- Q6: count_antibodies ------------------------------------------
    if "count_antibodies" in response_by_key:
        q6_answer = response_by_key["count_antibodies"].get("final_answer", "")
        missing_ids = [aid for aid in EXPECTED_ANTIBODY_IDS if aid not in q6_answer]
        functional_results["count_antibodies"] = {
            "expected_count": EXPECTED_ANTIBODY_COUNT,
            "expected_ids": sorted(EXPECTED_ANTIBODY_IDS),
            "missing_ids": missing_ids,
            "answer_preview": q6_answer[:300],
        }
        assert str(EXPECTED_ANTIBODY_COUNT) in q6_answer, (
            f"Q6 (count_antibodies) FAILED: expected {EXPECTED_ANTIBODY_COUNT} "
            f"antibodies in the DB but the agent's final answer does not "
            f"mention this count. Final answer was:\n{q6_answer[:1000]}"
        )
        assert not missing_ids, (
            f"Q6 (count_antibodies) FAILED: the agent's final answer is "
            f"missing antibody id(s) {missing_ids} (expected all of "
            f"{sorted(EXPECTED_ANTIBODY_IDS)}). Final answer was:\n{q6_answer[:1000]}"
        )
        logger.info(
            f"  Q6 count_antibodies: ✅ {EXPECTED_ANTIBODY_COUNT} antibodies, ids={sorted(EXPECTED_ANTIBODY_IDS)}"
        )
    else:
        logger.info("  Q6 count_antibodies: SKIPPED (not in query sequence).")

    # ---- Q7: ask_recent_experiment_id ----------------------------------
    if "ask_recent_experiment_id" in response_by_key:
        q7_answer = response_by_key["ask_recent_experiment_id"].get("final_answer", "")
        functional_results["ask_recent_experiment_id"] = {
            "expected_experiment_id": created_experiment_id,
            "answer_preview": q7_answer[:300],
        }
        if created_experiment_id is None:
            logger.warning(
                "  Q7 ask_recent_experiment_id: SKIPPED (Q1 was not run, so "
                "no reference experiment_id to assert against)."
            )
        else:
            assert str(created_experiment_id) in q7_answer, (
                f"Q7 (ask_recent_experiment_id) FAILED: the user asked for "
                f"the id of the experiment just created in Q1 — expected "
                f"{created_experiment_id}, but the agent's final answer "
                f"does not mention this id. This usually means Q1 silently "
                f"failed to create the experiment (the agent then answers "
                f"'no experiment was created'). Final answer was:\n"
                f"{q7_answer[:1500]}"
            )
            logger.info(f"  Q7 ask_recent_experiment_id: ✅ reports experiment {created_experiment_id} (matches Q1)")
    else:
        logger.info("  Q7 ask_recent_experiment_id: SKIPPED (not in query sequence).")

    logger.info("=" * 60)
    return functional_results, created_experiment_id


def verify_functional_correctness(
    per_query_responses: list[dict[str, Any]],
    workspace_dir: Path,
    report_dir: Path,
) -> tuple[dict[str, dict[str, Any]], int | None]:
    """Dispatch functional checks to the group that actually ran.

    Each group verifier self-gates on the query keys present in
    ``per_query_responses``, so only the group that was replayed is checked.
    """
    response_by_key: dict[str, dict[str, Any]] = {r["query_key"]: r for r in per_query_responses}

    logger.info("=" * 60)
    logger.info("Functional correctness checks:")

    functional_results: dict[str, dict[str, Any]] = {}
    functional_results.update(verify_tc_answer_assertions(response_by_key, report_dir))
    functional_results.update(verify_tcw_answer_assertions(response_by_key, report_dir))
    functional_results.update(verify_tcw_database_effects(response_by_key))
    default_results, created_experiment_id = verify_default_replay_assertions(
        response_by_key, workspace_dir, report_dir
    )
    functional_results.update(default_results)

    functional_report_path = report_dir / "functional_results_v3.json"
    functional_report_path.write_text(
        json.dumps(functional_results, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    logger.info(f"Functional results report: {functional_report_path}")
    logger.info("=" * 60)
    return functional_results, created_experiment_id
