#!/usr/bin/env bash
set -euo pipefail

# ===== DataOps OpenAPI configuration =====
DATAOPS_BASE_URL="${DATAOPS_BASE_URL:-https://dataops.example.com/openapi}"
DATAOPS_APPID="${DATAOPS_APPID:-}"
DATAOPS_SECRET_KEY="${DATAOPS_SECRET_KEY:-}"
DATAOPS_SERVICE_INSTANCE_ID="${DATAOPS_SERVICE_INSTANCE_ID:-}"
DATAOPS_SOURCE_TYPE="${DATAOPS_SOURCE_TYPE:-hive}"
DATAOPS_HIVE_RESOURCE_NAME="${DATAOPS_HIVE_RESOURCE_NAME:-hive_cluster_a}"
DATAOPS_CLICKHOUSE_RESOURCE_NAME="${DATAOPS_CLICKHOUSE_RESOURCE_NAME:-}"
DATAOPS_EXEC_USER="${DATAOPS_EXEC_USER:-alice}"
DATAOPS_ENGINE="${DATAOPS_ENGINE:-}"
DATAOPS_REQUEST_TIMEOUT_SEC="${DATAOPS_REQUEST_TIMEOUT_SEC:-30}"
DATAOPS_MCP_HOST="${DATAOPS_MCP_HOST:-0.0.0.0}"
DATAOPS_MCP_PORT="${DATAOPS_MCP_PORT:-8767}"
# =========================================

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 优先使用 venv，如果不存在则使用系统 python
if [[ -x "${DIR}/.venv/bin/python" ]]; then
    PYTHON="${DIR}/.venv/bin/python"
elif command -v python3 &>/dev/null; then
    PYTHON="python3"
else
    PYTHON="python"
fi

export DATAOPS_BASE_URL DATAOPS_APPID DATAOPS_SECRET_KEY DATAOPS_SERVICE_INSTANCE_ID
export DATAOPS_SOURCE_TYPE DATAOPS_HIVE_RESOURCE_NAME DATAOPS_CLICKHOUSE_RESOURCE_NAME
export DATAOPS_EXEC_USER DATAOPS_ENGINE DATAOPS_REQUEST_TIMEOUT_SEC
export DATAOPS_MCP_HOST DATAOPS_MCP_PORT

exec "${PYTHON}" "${DIR}/dataops_mcp_server.py" "$@"
