"""BIRD Agent-owned constants."""

BIRD_PROMPT_PREFIX = "agents/bird/prompts"

DEFAULT_BIRD_REFLECTOR_THRESHOLD: float = 0.9
DEFAULT_BIRD_NUM_WORKERS: int = 1
DEFAULT_BIRD_REF_RETRIES: int = 2
DEFAULT_BIRD_PREVIEW_LIMIT: int = 5
DEFAULT_BIRD_CELL_TRUNCATE_LENGTH: int = 500
DEFAULT_BIRD_SEMANTIC_TABLE_LIST_LIMIT: int = 1000
DEFAULT_BIRD_SEMANTIC_TABLE_COLUMNS_LIMIT: int = 1000
DEFAULT_BIRD_SEMANTIC_JOINABLE_TABLES_LIMIT: int = 1000
DEFAULT_BIRD_SQLITE_TIMEOUT: int = 30
DEFAULT_BIRD_SQLITE_PROGRESS_INTERVAL: int = 10000
