-- DataLink SQLite schema for dual-layer graph storage

-- Nodes table: all node types in one table, differentiated by type field
CREATE TABLE IF NOT EXISTS nodes (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,           -- 'column', 'table', 'concept', 'entity'
    name TEXT NOT NULL,
    properties TEXT,              -- JSON blob
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Edges table: all edge types, with confidence scores
-- NOTE: NO ON DELETE CASCADE on source_id/target_id!
-- INSERT OR REPLACE on nodes triggers an internal DELETE+INSERT,
-- which would cascade-delete all referencing edges — destroying
-- existing graph relationships on every node property update.
-- Edge cleanup is handled explicitly by remove_table /
-- cleanup_orphaned_semantic_nodes instead.
CREATE TABLE IF NOT EXISTS edges (
    id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL,
    target_id TEXT NOT NULL,
    type TEXT NOT NULL,           -- edge type enum values
    confidence REAL DEFAULT 1.0,
    properties TEXT,              -- JSON blob
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Column profiles table
-- NOTE: NO ON DELETE CASCADE — same reason as edges.
-- Profile cleanup is handled explicitly by remove_table.
CREATE TABLE IF NOT EXISTS column_profiles (
    id TEXT PRIMARY KEY,
    column_id TEXT NOT NULL,
    properties TEXT,              -- JSON blob with all profile stats
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Metadata table: stores build info and config
CREATE TABLE IF NOT EXISTS metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Pending edges: edges whose source/target nodes don't yet exist in the graph
-- (e.g., FK referencing a table from a datasource not yet added)
-- No FK constraints on source_id/target_id — they are allowed to reference non-existent nodes.
CREATE TABLE IF NOT EXISTS pending_edges (
    id TEXT PRIMARY KEY,
    source_id TEXT NOT NULL,     -- may not exist in nodes table
    target_id TEXT NOT NULL,     -- may not exist in nodes table
    type TEXT NOT NULL,
    confidence REAL DEFAULT 1.0,
    properties TEXT,             -- JSON blob
    missing_endpoints TEXT,      -- JSON array: ["source"] / ["target"] / ["source","target"]
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_nodes_type ON nodes(type);
CREATE INDEX IF NOT EXISTS idx_nodes_name ON nodes(name);
CREATE INDEX IF NOT EXISTS idx_edges_source ON edges(source_id);
CREATE INDEX IF NOT EXISTS idx_edges_target ON edges(target_id);
CREATE INDEX IF NOT EXISTS idx_edges_type ON edges(type);
CREATE INDEX IF NOT EXISTS idx_edges_source_type ON edges(source_id, type);
CREATE INDEX IF NOT EXISTS idx_edges_target_type ON edges(target_id, type);
CREATE INDEX IF NOT EXISTS idx_edges_confidence ON edges(confidence);
CREATE INDEX IF NOT EXISTS idx_profiles_column ON column_profiles(column_id);
-- Node embeddings: vector index for semantic search
-- Stores embedding vectors generated by an embedding model (e.g., Qwen3-Embedding-4B).
-- When the user changes the embedding model, all rows must be rebuilt (mode=vec rebuild).
CREATE TABLE IF NOT EXISTS node_embeddings (
    node_id TEXT PRIMARY KEY,           -- references nodes.id (no FK constraint — embeddings are rebuilt independently)
    embedding_model TEXT NOT NULL,      -- model name that produced this vector (e.g., "Qwen/Qwen3-Embedding-4B")
    embedding_vector BLOB NOT NULL,     -- float32 array serialized via struct.pack
    searchable_text TEXT NOT NULL,      -- the text used to generate the embedding (for validation/debugging)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pending_source ON pending_edges(source_id);
CREATE INDEX IF NOT EXISTS idx_pending_target ON pending_edges(target_id);
CREATE INDEX IF NOT EXISTS idx_pending_type ON pending_edges(type);

-- Index for filtering embeddings by model (used during rebuild to check consistency)
CREATE INDEX IF NOT EXISTS idx_embeddings_model ON node_embeddings(embedding_model);
