# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
from contextlib import redirect_stdout
from pathlib import Path
from typing import Any

from loguru import logger  # type: ignore[reportMissingImports]

from dataagent.core.context.message_history import deserialize_message, serialize_message
from dataagent.core.errors import DataAgentError
from dataagent.core.swarm.worker_memory import strip_subagent_runtime_fields
from dataagent.core.swarm.worker_result import synthesize_worker_result, worker_session_id
from dataagent.interface.sdk.agent import DataAgent
from dataagent.utils.log import LoggerConfig, dataagent_log_context, reconfigure
from dataagent.utils.runtime_paths import SUBAGENT_OUTPUT_DIR_ENV, resolve_user_root, validate_user_id


def main() -> int:
    """Run a sub-agent process and emit a JSON payload to stdout."""
    parser = argparse.ArgumentParser(description="Run sub DataAgent and output result as JSON")
    parser.add_argument("--query", required=True, help="User query for sub agent")
    parser.add_argument("--config", required=True, help="YAML config path for sub agent")
    parser.add_argument(
        "--user-id",
        dest="user_id",
        default=None,
        help="Optional user id to pass through to sub agent (should match main agent user_id).",
    )
    parser.add_argument(
        "--session-id",
        dest="session_id",
        default=None,
        help="Optional session id to pass through to sub agent",
    )
    parser.add_argument(
        "--sub-id",
        dest="sub_id",
        type=int,
        required=True,
        help="Required sub agent id generated by the parent process.",
    )
    parser.add_argument(
        "--initial-state-file",
        dest="initial_state_file",
        default=None,
        help="Optional JSON file containing parent-prepared initial_state.",
    )
    parser.add_argument(
        "--trace-id",
        dest="trace_id",
        default=None,
        help="Optional shared trace id from the parent process.",
    )

    args = parser.parse_args()
    parent_session_id = str(args.session_id or "default_session")
    sub_id = int(args.sub_id)
    trace_id = str(args.trace_id or "").strip() or None

    with dataagent_log_context(
        session_id=worker_session_id(parent_session_id, sub_id),
        user_id=str(args.user_id or "anonymous"),
        sub_id=sub_id,
        trace_id=trace_id,
        agent_name="subagent",
    ):
        try:
            if not Path(args.config).is_file():
                raise FileNotFoundError(f"Config YAML not found: {args.config}")

            with redirect_stdout(sys.stderr):
                result = asyncio.run(
                    _run_agent(
                        args.query,
                        args.config,
                        user_id=args.user_id,
                        session_id=args.session_id,
                        sub_id=sub_id,
                        initial_state_file=args.initial_state_file,
                    )
                )
            resumed = _initial_state_file_has_messages(args.initial_state_file)
            worker_result = synthesize_worker_result(
                final_state=result,
                sub_id=sub_id,
                parent_session_id=parent_session_id,
                resumed=resumed,
            )
            jsonable_result = _to_jsonable(result)
            payload = {
                "worker_result": worker_result.to_dict(),
                "worker_persistence": {
                    "messages": _to_jsonable((result or {}).get("messages", [])) if isinstance(result, dict) else [],
                    "state": _build_worker_persistence_state(jsonable_result=jsonable_result),
                },
                "subagent_final_state": json.dumps(jsonable_result, ensure_ascii=False)
                if isinstance(jsonable_result, dict)
                else str(jsonable_result),
                "assistant_reply": worker_result.final_answer,
                "sub_id": sub_id,
            }
            sys.stdout.write(json.dumps(payload, ensure_ascii=False))
            sys.stdout.flush()
            return 0
        except Exception as exc:
            error = DataAgentError.from_exception(exc, component="subagent", trace_id=trace_id)
            fact = error.fact
            extra = f"sub_id={sub_id}"
            if extra not in fact:
                fact = f"{fact}；{extra}"
            error = DataAgentError(
                source=error.source,
                component=error.component,
                fact=fact,
                trace_id=error.trace_id,
            )
            logger.exception(
                "sub_agent_entry failed source={} trace_id={}",
                error.source,
                error.trace_id,
            )
            failed = synthesize_worker_result(
                final_state={},
                sub_id=sub_id,
                parent_session_id=parent_session_id,
                status="failed",
                error=error,
            )
            payload = {"worker_result": failed.to_dict(), "sub_id": sub_id}
            sys.stdout.write(json.dumps(payload, ensure_ascii=False))
            sys.stdout.flush()
            return 1


def _resolve_subagent_identity(
    *, user_id: str | None, session_id: str | None, sub_id: int | None
) -> tuple[str, str, int]:
    resolved_user_id = str(user_id).strip() if user_id is not None and str(user_id).strip() else "anonymous"
    resolved_user_id = validate_user_id(resolved_user_id)
    parent_session_id = (
        str(session_id).strip() if session_id is not None and str(session_id).strip() else "default_session"
    )
    if sub_id is None:
        raise ValueError("sub_id is required for subagent persistence.")
    resolved_sub_id = int(sub_id)
    return resolved_user_id, f"subagent_{parent_session_id}_{resolved_sub_id}", resolved_sub_id


async def _run_agent(
    query: str,
    config_path: str,
    *,
    user_id: str | None = None,
    session_id: str | None = None,
    sub_id: int | None = None,
    initial_state_file: str | None = None,
) -> Any:
    """Run a sub-agent process and return its final state."""
    resolved_user_id, resolved_session_id, resolved_sub_id = _resolve_subagent_identity(
        user_id=user_id, session_id=session_id, sub_id=sub_id
    )
    log_path = (resolve_user_root(user_id=resolved_user_id) / "logs" / f"{resolved_session_id}.log").resolve()
    reconfigure(LoggerConfig(process_name="subagent", file_path=str(log_path), file_path_explicit=True))
    agent = DataAgent.from_config(Path(config_path))
    shared_output_dir = os.getenv(SUBAGENT_OUTPUT_DIR_ENV, "").strip()
    if shared_output_dir:
        allow_paths = agent.config.get("WORKSPACE.allow_path", [])
        allow_paths = list(allow_paths) if isinstance(allow_paths, list) else []
        if shared_output_dir not in allow_paths:
            allow_paths.append(shared_output_dir)
        agent.config.set("WORKSPACE.allow_path", allow_paths)
    initial_state = _load_initial_state_file(initial_state_file)
    defaults = {
        "user_query": query,
        "complete": False,
        "user_id": resolved_user_id,
        "session_id": resolved_session_id,
        "run_id": 0,
        "sub_id": resolved_sub_id,
    }
    for key, value in defaults.items():
        initial_state.setdefault(key, value)
    return await agent.chat(query, initial_state=initial_state)


def _load_initial_state_file(initial_state_file: str | None) -> dict[str, Any]:
    if not initial_state_file:
        return {}
    path = Path(initial_state_file)
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        return {}
    messages = payload.get("messages")
    if isinstance(messages, list):
        restored = []
        for item in messages:
            if isinstance(item, dict):
                msg = deserialize_message(item)
                if msg is not None:
                    restored.append(msg)
        payload["messages"] = restored
    return payload


def _initial_state_file_has_messages(initial_state_file: str | None) -> bool:
    """Return True only when the parent-provided initial state contains history messages."""
    if not initial_state_file:
        return False
    try:
        payload = json.loads(Path(initial_state_file).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    messages = payload.get("messages") if isinstance(payload, dict) else None
    return isinstance(messages, list) and len(messages) > 0


def _build_worker_persistence_state(*, jsonable_result: Any) -> dict[str, Any]:
    """Build the state snapshot persisted by the parent for debugging and reuse."""
    state = dict(jsonable_result) if isinstance(jsonable_result, dict) else {"result": jsonable_result}
    state.pop("messages", None)
    return strip_subagent_runtime_fields(state)


def _to_jsonable(obj: Any) -> Any:
    """Best-effort conversion to JSON-serializable types."""
    try:
        import dataclasses
    except Exception:  # pragma: no cover
        dataclasses = None  # type: ignore[assignment]

    converted: Any
    if obj is None:
        converted = None
    elif isinstance(obj, (str, int, float, bool)):
        converted = obj
    elif isinstance(obj, (tuple, list)):
        converted = [_to_jsonable(i) for i in obj]
    elif isinstance(obj, dict):
        converted = {str(k): _to_jsonable(v) for k, v in obj.items()}
    elif hasattr(obj, "content") and obj.__class__.__name__ in {
        "HumanMessage",
        "AIMessage",
        "ToolMessage",
        "SystemMessage",
    }:
        try:
            converted = serialize_message(obj)
        except Exception:
            converted = str(obj)
    elif dataclasses is not None and dataclasses.is_dataclass(obj) and not isinstance(obj, type):
        converted = {str(k): _to_jsonable(v) for k, v in dataclasses.asdict(obj).items()}
    else:
        converted = str(obj)
    return converted


if __name__ == "__main__":
    raise SystemExit(main())
